# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Compendia Documentation
email: notadampaul@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the documentation homepage for the project whose working
  title is *Compendia*. Its development will be catalogued here, until
  it is finished, if that ever happens. At that point, this will become
  the working documentation for the resource.
baseurl: "/compendia" # the subpath of your site, e.g. /blog
url: "http://adampaul.github.io" # the base hostname & protocol for your site
github_username:  adam-paul

# Build settings
markdown: kramdown
